# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2f0b0f48d9953a3464c461fb3164c735b583f4b60270f90d1c4543f220011bbda03ddcb196798d68d1e2d4f2bbd880b6cba935bdddf64868a71a961b379f4a1

test:
  secret_key_base: bba7f396e70bba6553b4afc69096e7f025aaf804597525310cc695ec9748b6a308d83c0b9b7edbd5f8103a8de2cf98d58a44f5fdba7c3c34a9c8284aa24d8505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
